version: '3'

services: 
    app:
        build: 
            context: node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 120s node index.js
        networks: 
            - app-network
        tty: true
        ports: 
            - "3000"
        depends_on: 
            - db
   
    db:
        build:
            context: mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        networks: 
            - app-network
        tty: true
        environment: 
            - MYSQL_ROOT_PASSWORD=root

   

    nginx: 
        build:
            context: nginx
        container_name: nginx
        networks: 
            - app-network
        ports:
            - "8080:80"
        depends_on: 
            - app
networks: 
    app-network:
        driver: bridge